### ISSUE TITLE
External dns is not creating alias record instead creating CNAME record 

### ISSUE THREAD

**Issue by shankarsundaram** [bitnami/bitnami-docker-external-dns#10]
external dns is creating only CNAME record even the AWSPreferCNAME:false for aws alb ingress controller
I'm expecting for alias record but it is creating only cname.

external dns version: bitnami/external-dns:0.7.4-debian-10-r29
alb ingress version: aws-alb-ingress-controller:v1.1.8

external-dns.alpha.kubernetes.io/hostname: <dnsname which resolves to alb>

Args:
  --log-level=info
  --log-format=text
  --events
  --policy=upsert-only
  --provider=aws
  --registry=txt
  --interval=10m
  --source=service
  --source=ingress
  --aws-batch-change-size=1000

This is happening recently

**Comment by javsalgar** [comment]
Hi,

Note that we do not add any extra Bitnami configuration to the container, we just execute the binary. In this case, I would advise you to report the issue to the upstream devs. https://github.com/kubernetes-sigs/external-dns

**Comment by shankarsundaram** [comment]
> Hi,
> 
> Note that we do not add any extra Bitnami configuration to the container, we just execute the binary. In this case, I would advise you to report the issue to the upstream devs. https://github.com/kubernetes-sigs/external-dns

Thanks. I reported my issue to the upstream devs. https://github.com/kubernetes-sigs/external-dns

**Comment by shankarsundaram** [comment]
this was due to issue with aws region https://github.com/kubernetes-sigs/external-dns/pull/1832
