### ISSUE TITLE
Multiarch image

### ISSUE THREAD

**Issue by cam3ron2** [bitnami/bitnami-docker-external-dns#12]
### Name and Version

bitnami/external-dns:0.10.2

### What is the problem this feature will solve?

external-dns image is currently only built for a single CPU architecture - amd64. 

This is an inconvenience for users like myself that otherwise run arm64 kubernetes clusters -- i keep a tiny amd64 node in-cluster exclusively for external-dns. 

### What is the feature you are proposing to solve the problem?

The image that external-dns uses as a base (bitnami/minideb:buster) is already multiarch and supports arm64/amd64, however the artifact `https://downloads.bitnami.com/files/stacksmith/external-dns-0.11.0-0-linux-amd64-debian-10.tar.gz` appears to only exist for amd64. As long as its not too much work to recompile that app for arm64 it should take minimal work to make a multiarch/arm64 image variant available. 

### What alternatives have you considered?

The alternative would be that we could build our own multiarch image to run externaldns, or stop using the bitnami charts

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
