### ISSUE TITLE
Does chart support `--rfc2136-min-ttl`?

### ISSUE THREAD

**Issue by stefanlasiewski** [bitnami/bitnami-docker-external-dns#5]
**Description**

As of external-dns 0.7, the rfc2136 provider provides a new flag `--rfc2136-min-ttl` set a default TTL for all records. This is a pretty important improvement because otherwise the default TTL is 0 and many DNS administrators frown upon that.

If this chart supports the same option, I cannot figure out what the correct name is. Is it supported at all, and what is the name of the value?

**Comment by joancafom** [comment]
Hey @stefanlasiewski !

This Chart is based on the tool ExternalDNS for Kubernetes. You can use [annotations](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/ttl.md) on Services in order to modify the default TTL time. You can use the available property `service.annotations` in order to add multiple annotations to the different Services. 

Thanks!

**Comment by stefanlasiewski** [comment]
Hi @joancafom,

I'm actually specifically referring to this feature in v0.7.0 (see the [CHANGELOG](https://github.com/kubernetes-sigs/external-dns/blob/master/CHANGELOG.md#v070---2020-03-10)

> Rfc2136: Add option to define minimum TTL (#1412) @ouzklcn
 
[#1412](https://github.com/kubernetes-sigs/external-dns/pull/1412/files) adds `--rfc2136-min-ttl` flag to the commandline. Also, I see a config parameter `RFC2136MinTTL` but I don't understand how that would be used in this chart.

**Comment by joancafom** [comment]
Hello @stefanlasiewski ,

Thanks for the CHANGELOG and the reference to the original issue. It is an interesting feature to have for sure. We currently support the rest of [flags](https://github.com/bitnami/charts/blob/3ea544973c284a7290ebb79eef25800ae868140c/bitnami/external-dns/values.yaml#L294), so adding this new one should not be a problem. I will try to implement the changes in a new PR and link back to this issue to let you know.

Good news is that even if the feature is not implemented yet, you can still specify additional arguments to chart by using the [property](https://github.com/bitnami/charts/blob/3ea544973c284a7290ebb79eef25800ae868140c/bitnami/external-dns/values.yaml#L372) `extraArgs`.

Thanks!

**Comment by stefanlasiewski** [comment]
Thanks for the tip about `extraArgs`, I'll give that a try.

**Comment by stefanlasiewski** [comment]
How would I use the `extraArgs` option? I tried the following and it didn't add the TTL:

    extraArgs: { "RFC2136MinTTL=2m" }

The logs show me this after upgrading the chart with this new value:

    RFC2136MinTTL:0s

**Comment by joancafom** [comment]
Hi @stefanlasiewski ,

I created a PR with the changes you proposed and soon it will be available in the main Chart. Regarding the correct method of use of the `extraArgs` option, you may proceed as follows:

```yaml
## Extra Arguments to passed to external-dns
##
extraArgs:
  rfc2136-min-ttl: "20s"
```

Now the log should show something like this:

```
RFC2136MinTTL:20s
```

Hope it helps, thanks!
