### ISSUE TITLE
add support for private rootca.

### ISSUE THREAD

**Issue by jsfrerot** [bitnami/bitnami-docker-external-dns#9]
**Description**

Getting an "x509: certificate signed by unknown authority" error when using internal pdns server with custom certificate.

**Steps to reproduce the issue:**

1. Have a pdns server with private RootCa
2. deploy external-dns with helm using pdns provider
3. look at pod logs to notice the "x509: certificate signed by unknown authority" error message

**Describe the results you received:**

Getting a "x509: certificate signed by unknown authority" error message

**Describe the results you expected:**

Be able to provide our own RootCa to prevent this error.

**Version**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Deployed on an internal private k8s cluster using helm

**Comment by javsalgar** [comment]
Hi,

I've been checking and we could add the following parameters.

```
--pdns-tls-enabled
--tls-ca
```

Source https://github.com/kubernetes-sigs/external-dns/blob/master/pkg/apis/externaldns/types.go

For the time being, you could use the `extraArgs` value to add the missing elements you require. If you need to mount the CA, you could use `extraVolumes` and `extraVolumeMounts`. Could you try with these and let us know if it works? If so, we would work on adding support using the values. If you want to speed up the process, feel free to submit a PR and we will review it.
